version: "2"
services:
  tests:
    build:
      context: .
    volumes:
      - ".:/plugin:ro"
  lint:
    image: buildkite/plugin-linter
    command: ["--name", "commonlit/aws-sm"]
    volumes:
      - ".:/plugin:ro"
